platform :ios, '7.0'
inhibit_all_warnings!

target 'TestLBXNetWork' do

pod 'AFNetworking','~> 3.0'
pod 'YYCache','~>1.0.4'
pod 'LBXNetWork', path:"../"

pod 'MBProgressHUD'
pod 'Toast', '~> 3.1.0'
pod 'LBXAlertAction'

end
